regions_dict = {
    "us-east-1": "AWS Virginia",
    "us-east-2": "AWS Ohio",
    "us-east1": "GCP South Carolina",
    "us-east4": "GCP Virginia",
    "us-ashburn-1": "OCI Virginia",
    "us-central1": "GCP Iowa",
    "us-chicago-1": "OCI Chicago",
    "us-west-1": "AWS California",
    "us-west-2": "AWS Oregon",
    "us-west1": "GCP Oregon",
    "us-sanjose-1": "OCI San Jose",
    "asia-northeast3": "GCP Seoul",
    "ap-northeast-1": "AWS Tokyo",
    "ap-northeast-3": "AWS Osaka",
    "asia-southeast1": "GCP Singapore",
    "ap-southeast-3": "OCI Singapore",
    "ap-melbourne-1": "OCI Melbourne",
    "ca-central-1": "AWS Montreal",
    "ca-toronto-1": "OCI Toronto",
    "me-west1": "OCI Bahrain",
    "sa-east-1": "AWS São Paulo",
    "eu-central-1": "AWS Frankfurt",
    "eu-west-1": "AWS Ireland",
    "eu-west-2": "AWS London",
    "eu-west-3": "AWS Paris",
    "europe-west4": "GCP Netherlands",
    "eu-frankfurt-1": "OCI Frankfurt",
    "eu-paris-1": "OCI Paris",
    "uk-london-1": "OCI London",
    "eu-north-1": "AWS Stockholm"
}
